### PR TITLE
The 1.4.0 release is missing a migration

### PR DESCRIPTION
**Pull request by bradmontgomery**
This PR adds the missing migration.

### CODE REVIEW

**Comment by ivanvenosdel** [comment]
Thanks! I am hoping to try to reproduce the issue and verify the fix this weekend or Monday. How did you come across it?
I also see that the tests are complaining. I wonder if the project is behind on a package.

**Comment by bradmontgomery** [comment]
I pip-installed andablog, and my django installation started complaining about missing migrations (django 1.8, python 3.4). So, I ran `./manage.py makemigrations` and discovered that it was this package.

**Comment by ivanvenosdel** [comment]
I fixed up a few things on master that should let you have a proper test run. Would you mind rebasing this remote branch against the most recent changes on master?

**Comment by bradmontgomery** [comment]
updated! :sunglasses:

**Comment by ivanvenosdel** [comment]
OK, almost there. Looks like andablog (and other projects) were bit by [this Django issue](https://code.djangoproject.com/ticket/23226).

I don't want to see an issue like this come up again so I now have a branch that [reproduces the issue](https://travis-ci.org/WimpyAnalytics/django-andablog/builds/78115638) with an automated test. 

Would you mind again rebasing and pushing your branch but this time off of origin/reproduce30? That branch has a test that reproduces the issue. If your change fixes the issue, as I think it should, the build should pass and we will be ready to merge!

**Comment by bradmontgomery** [comment]
Argh. Sorry for letting this slip by... rebase coming soon.

**Comment by ivanvenosdel** [comment]
Oops you did the second rebase last week and I didn't realize it. Should have a release today then!

**Comment by ivanvenosdel** [comment]
New release is out.
https://pypi.python.org/pypi/django-andablog/1.4.1

**Comment by bradmontgomery** [comment]
Awesome! Thank you! :+1:

**Pull request merged**
